[package]
name = "asm_macro"
version = "0.1.0"
authors = ["Elanchezhiyan Elango <elan@elanelango.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro=true

[dependencies]