[package]
authors = ["Elanchezhiyan Elango <elan@elanelango.com>"]
edition = "2018"
name = "compiler"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0"
quick-xml = "^0"
